# Generated by Django 2.1.2 on 2018-10-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='amount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.IntegerField()),
                ('intern', models.IntegerField()),
                ('company', models.IntegerField()),
                ('city', models.IntegerField()),
            ],
        ),
    ]
