# Generated by Django 2.1.2 on 2018-10-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Posting_title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('Internship_discription', models.TextField()),
                ('Location', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
