# Generated by Django 2.1.2 on 2018-10-14 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_app_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='app_deadline',
        ),
    ]
