# Generated by Django 2.1.2 on 2018-10-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20181016_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply',
            old_name='Cover_letter',
            new_name='address',
        ),
        migrations.AddField(
            model_name='apply',
            name='birth',
            field=models.CharField(default='bangla', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apply',
            name='contact',
            field=models.CharField(default='jh', max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apply',
            name='email',
            field=models.EmailField(default='y', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apply',
            name='full_name',
            field=models.CharField(default='jh', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apply',
            name='nationality',
            field=models.CharField(default='bd', max_length=30),
            preserve_default=False,
        ),
    ]
