# Generated by Django 2.1.2 on 2018-10-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_remove_post_app_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='deadline',
            field=models.CharField(default='oct', max_length=50),
            preserve_default=False,
        ),
    ]
