# Generated by Django 2.1.2 on 2018-10-16 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_post_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salery', models.IntegerField()),
                ('letter', models.TextField()),
            ],
        ),
    ]
