# Generated by Django 2.1.2 on 2018-10-16 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_apply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply',
            old_name='letter',
            new_name='Cover_letter',
        ),
        migrations.RenameField(
            model_name='apply',
            old_name='salery',
            new_name='Expected_salery',
        ),
    ]
